export const ALL_NOTE_REQUEST = 'ALL_NOTE_REQUEST';
export const ALL_NOTE_SUCCESS = 'ALL_NOTE_SUCCESS';
export const ALL_NOTE_FAIL = 'ALL_NOTE_FAIL';

export const ADMIN_NOTE_REQUEST = 'ADMIN_NOTE_REQUEST';
export const ADMIN_NOTE_SUCCESS = 'ADMIN_NOTE_SUCCESS';
export const ADMIN_NOTE_FAIL = 'ADMIN_NOTE_FAIL';

export const NEW_NOTE_REQUEST = 'NEW_NOTE_REQUEST';
export const NEW_NOTE_SUCCESS = 'NEW_NOTE_SUCCESS';
export const NEW_NOTE_RESET = 'NEW_NOTE_RESET';
export const NEW_NOTE_FAIL = 'NEW_NOTE_FAIL';

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_RESET = 'UPDATE_NOTE_RESET';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_RESET = 'DELETE_NOTE_RESET';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST';
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_SUCCESS';
export const NOTE_DETAILS_FAIL = 'NOTE_DETAILS_FAIL';
export const NOTE_DELETES_RESET = 'NOTE_DELETE_RESETS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
