export const ALL_SUBSCRIPTION_REQUEST = 'ALL_SUBSCRIPTION_REQUEST';
export const ALL_SUBSCRIPTION_SUCCESS = 'ALL_SUBSCRIPTION_SUCCESS';
export const ALL_SUBSCRIPTION_FAIL = 'ALL_SUBSCRIPTION_FAIL';

export const ADMIN_SUBSCRIPTION_REQUEST = 'ADMIN_SUBSCRIPTION_REQUEST';
export const ADMIN_SUBSCRIPTION_SUCCESS = 'ADMIN_SUBSCRIPTION_SUCCESS';
export const ADMIN_SUBSCRIPTION_FAIL = 'ADMIN_SUBSCRIPTION_FAIL';

export const NEW_SUBSCRIPTION_REQUEST = 'NEW_SUBSCRIPTION_REQUEST';
export const NEW_SUBSCRIPTION_SUCCESS = 'NEW_SUBSCRIPTION_SUCCESS';
export const NEW_SUBSCRIPTION_RESET = 'NEW_SUBSCRIPTION_RESET';
export const NEW_SUBSCRIPTION_FAIL = 'NEW_SUBSCRIPTION_FAIL';

export const UPDATE_SUBSCRIPTION_REQUEST = 'UPDATE_SUBSCRIPTION_REQUEST';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_RESET = 'UPDATE_SUBSCRIPTION_RESET';
export const UPDATE_SUBSCRIPTION_FAIL = 'UPDATE_SUBSCRIPTION_FAIL';

export const DELETE_SUBSCRIPTION_REQUEST = 'DELETE_SUBSCRIPTION_REQUEST';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_RESET = 'DELETE_SUBSCRIPTION_RESET';
export const DELETE_SUBSCRIPTION_FAIL = 'DELETE_SUBSCRIPTION_FAIL';

export const SUBSCRIPTION_DETAILS_REQUEST = 'SUBSCRIPTION_DETAILS_REQUEST';
export const SUBSCRIPTION_DETAILS_SUCCESS = 'SUBSCRIPTION_DETAILS_SUCCESS';
export const SUBSCRIPTION_DETAILS_FAIL = 'SUBSCRIPTION_DETAILS_FAIL';
export const SUBSCRIPTION_DELETES_RESET = 'SUBSCRIPTION_DELETE_RESETS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
